_target_: src.agents.a2c.A2CAgent
_recursive_: False
network_cfg:
  actor: ${network.actor}
  critic: ${network.critic}
optimizer_cfg: ${optimizer}
n_env: 16
batch_size: 128
learning_starts: 128
discount_gamma: 0.9
entropy_coef: 0.001
value_loss_coef: 1
max_grad_norm: 0.5
max_episode_length: 200
seed: ${seed}
